# prometheus config
global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'kyle-jmx-kafka'
    static_configs:
      - targets:
        - kyle-kafka-kafka01.foo.bar:7071
        - kyle-kafka-kafka02.foo.bar:7071
        - kyle-kafka-kafka03.foo.bar:7071

  - job_name: 'kyle-kafka-nodes'
    static_configs:
      - targets:
          - kyle-kafka-kafka01.foo.bar:9100
          - kyle-kafka-kafka02.foo.bar:9100
          - kyle-kafka-kafka03.foo.bar:9100

  - job_name: 'kyle-kafka-exporter'
    static_configs:
      - targets:
          - kyle-kafka-kafka01.foo.bar:9308
          - kyle-kafka-kafka02.foo.bar:9308
          - kyle-kafka-kafka03.foo.bar:9308