zookeeperversion: zookeeper-3.5.9
myid: "{{ inventory_hostname | regex_search('(kyle-kafka-zk0[0-9]\\.foo\\.bar)') | regex_replace('\\.foo\\.bar', '') | regex_replace('^kyle-kafka-zk0', '') }}"
dir_path: /data/zk